alias gb="git branch"
alias gco="git checkout"
alias gcm="git commit --verbose -S -m"
alias gs="git status"
alias gl="git log"
alias gd="git diff --color-words"
alias ls="ls -lahF --time-style=long-iso --color=auto --ignore=lost+found"
alias reload_profile=". ~/.bash_profile"
alias please="sudo"
alias open="xdg-open"
